apiVersion: apps/v1
kind: Deployment
metadata:
  name: odevelasticsearch
  labels:
    team: sosyalmedyadevelopersteam
spec:
  replicas: 1
  selector:
    matchLabels:
      elasticpod: pod-elasticsearch
  template:
    metadata:
      labels:
        elasticpod: pod-elasticsearch
    spec:
      containers:
        - image: elasticsearch:7.17.6
          name:  pod-elasticsearch
          resources:
            requests:
              memory: "1Gi"
              cpu: "0.1"
            limits:
              memory: "2Gi"
              cpu: "0.25"
          ports:
            - name:  elasticone
              containerPort: 9200
            - name:  elastictwo
              containerPort: 9300
          env:
            - name: discovery.type
              value: single-node
            - name: bootstrap.memory_lock
              value: "true"
            - name: "ES_JAVA_OPTS"
              value: "-Xms1024m -Xmx1024m"
            - name: config_server_url
              valueFrom:
                secretKeyRef:
                  name: yarismasecret
                  key: config_server_url
            - name: elastic_port
              valueFrom:
                secretKeyRef:
                  name: yarismasecret
                  key: elastic_port
            - name: zipkin_url
              valueFrom:
                secretKeyRef:
                  name: yarismasecret
                  key: zipkin_url
            - name: elastic_search_url
              valueFrom:
                secretKeyRef:
                  name: yarismasecret
                  key: elastic_search_url

            - name: auth_url
              valueFrom:
                secretKeyRef:
                  name: yarismasecret
                  key: auth_url
            - name: main_url
              valueFrom:
                secretKeyRef:
                  name: yarismasecret
                  key: main_url
            - name: user_url
              valueFrom:
                secretKeyRef:
                  name: yarismasecret
                  key: user_url




