apiVersion: apps/v1
kind: Deployment
metadata:
  name: userployment
  labels:
    team: tarismadevelopersteam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - image: javaboost2/userservice:v103
          name:  poduser
          resources:
            requests:
              memory: "1Gi"
              cpu: "0.1"
            limits:
              memory: "2Gi"
              cpu: "0.25"
          ports:
            - containerPort: 9092
          env:
            - name:  user_port
              valueFrom:
                secretKeyRef:
                  name: yarismasecret
                  key: user_port

            - name:  rabbitmq_host
              valueFrom:
                secretKeyRef:
                  name: yarismasecret
                  key: rabbitmq_host
            - name:  rabbitmq_port
              valueFrom:
                secretKeyRef:
                  name: yarismasecret
                  key: rabbitmq_port
            - name:  rabbitmq_username
              valueFrom:
                secretKeyRef:
                  name: yarismasecret
                  key: rabbitmq_username
            - name:  rabbitmq_password
              valueFrom:
                secretKeyRef:
                  name: yarismasecret
                  key: rabbitmq_password
            - name:  zipkin_url
              valueFrom:
                secretKeyRef:
                  name: yarismasecret
                  key: zipkin_url

            - name:  redis_host
              valueFrom:
                secretKeyRef:
                  name: yarismasecret
                  key: redis_host
            - name:  redis_port
              valueFrom:
                secretKeyRef:
                  name: yarismasecret
                  key: redis_port

            - name: auth_url
              valueFrom:
                secretKeyRef:
                  name: yarismasecret
                  key: auth_url
            - name: main_url
              valueFrom:
                secretKeyRef:
                  name: yarismasecret
                  key: main_url
            - name: user_url
              valueFrom:
                secretKeyRef:
                  name: yarismasecret
                  key: user_url

            - name: db_mongo_url
              valueFrom:
                secretKeyRef:
                  name: yarismasecret
                  key: db_mongo_url
            - name: db_mongo_username
              valueFrom:
                secretKeyRef:
                  name: yarismasecret
                  key: db_mongo_username
            - name: db_mongo_password
              valueFrom:
                secretKeyRef:
                  name: yarismasecret
                  key: db_mongo_password
            - name: db_mongo_port
              valueFrom:
                secretKeyRef:
                  name: yarismasecret
                  key: db_mongo_port
            - name: db_mongo_database
              valueFrom:
                secretKeyRef:
                  name: yarismasecret
                  key: db_mongo_database

            - name: config_server_url
              valueFrom:
                secretKeyRef:
                  name: yarismasecret
                  key: config_server_url