apiVersion: v1
kind: Secret
metadata:
  name: yarismasecret
type: Opaque
stringData:
  db_postgresql_username: 'postgres'
  db_postgresql_password: '123456'
  db_postgresql_url: 'jdbc:postgresql://10.64.1.49:5432/YarismaDB'
  db_mongo_username: 'bilgeadamuser'
  db_mongo_password: 'C[?K-6)pDZe]ju`-ROi%|or8C!G1ll'
  db_mongo_url: '10.64.1.25'
  db_mongo_port: '27017'
  db_mongo_database: 'bilgeyarisma'
  services_auth_clusterip: '10.68.9.248'
  services_main_clusterip: '10.68.8.115'
  services_user_clusterip: '10.68.10.214'
  services_configserver_clusterip: '10.68.9.132'
  services_elastic_clusterip: '10.68.14.205'
  elastic_search_url: 'http://10.64.1.55:9200'
  redis_host: '10.64.1.56'
  redis_port: '6379'
  rabbitmq_host: '10.64.1.58'
  rabbitmq_port: '5672'
  rabbitmq_username: 'bilgeuser'
  rabbitmq_password: 'B!lge123*'
  zipkin_url: 'http://10.64.1.57:9411'
  auth_port: '9090'
  main_port: '9091'
  user_port: '9092'
  configserver_port: '8888'
  elastic_port: '9099'
  auth_url: 'http://10.68.9.248:9090/'
  main_url: 'http://10.68.8.115:9091/'
  user_url: 'http://10.68.10.214:9092/'
  gateway_auth_url: 'http://10.68.9.248:9090'
  gateway_main_url: 'http://10.68.8.115:9091'
  gateway_user_url: 'http://10.68.10.214:9092'
  config_server_url: 'http://10.68.9.132:8888'


