apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-configserver
spec:
  selector:
    app: config-server
  type: ClusterIP
  ports:
    - name: config-server
      port: 8888
      targetPort: 8888